cd ~/challenges/cyberdayCTF/misc/PerfectMovement/
docker-compose build
cd ~/challenges/cyberdayCTF/misc/Pythonic/build/
docker-compose build
cd ~/challenges/cyberdayCTF/misc/QRCodes/
docker-compose build
cd ~/challenges/cyberdayCTF/web/42SQL/build/
docker-compose build
cd ~/challenges/cyberdayCTF/web/Jarred/build/
docker-compose build
cd ~/challenges/cyberdayCTF/web/Peek/build/
docker-compose build
