include:
- ./misc/PerfectMovement/compose.yaml
- ./misc/Pythonic/build/docker-compose.yaml
- ./misc/QRCodes/compose.yaml
- ./web/42SQL/build/docker-compose.yml
- ./web/Jarred/build/docker-compose.yml
- ./web/Peek/build/docker-compose.yml