(cd /root/challenges/cyberdayCTF/misc/PerfectMovement/ && docker-compose up &)
(cd /root/challenges/cyberdayCTF/misc/Pythonic/build/ && docker-compose up &)
(cd /root/challenges/cyberdayCTF/misc/QRCodes/ && docker-compose up &)
(cd /root/challenges/cyberdayCTF/web/42SQL/build/ && docker-compose up &)
(cd /root/challenges/cyberdayCTF/web/Jarred/build/ && docker-compose up &)
(cd /root/challenges/cyberdayCTF/web/Peek/build/ && docker-compose up &)
